import{a as w,S as v,i as a}from"./assets/vendor-C2ySes1p.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();async function d(r,e=1){const o="47477357-395d8a047c7c5012d361fddb9";return console.log("KEY:",o),(await w.get("https://pixabay.com/api/",{params:{key:o,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const S=new v(".gallery a",{captionsData:"alt",captionDelay:250}),u=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-more");function g(r){const e=r.map(o=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
        </a>
        <div class="info">
          <p><b>Likes</b>${o.likes}</p>
          <p><b>Views</b>${o.views}</p>
          <p><b>Comments</b>${o.comments}</p>
          <p><b>Downloads</b>${o.downloads}</p>
        </div>
      </li>`).join("");u.insertAdjacentHTML("beforeend",e),S.refresh()}const q=()=>u.innerHTML="",p=()=>m.classList.add("is-visible"),y=()=>m.classList.remove("is-visible"),h=()=>f.classList.remove("hidden"),b=()=>f.classList.add("hidden");let i="",n=1;const L=15,M=document.querySelector(".form"),P=document.querySelector(".load-more");M.addEventListener("submit",async r=>{if(r.preventDefault(),i=r.currentTarget.elements["search-text"].value.trim(),i===""){a.warning({message:"Please enter a search query!"});return}n=1,q(),b(),p();try{const e=await d(i,n);if(e.hits.length===0){a.error({message:"Sorry, no images found!"});return}g(e.hits),e.totalHits>L&&h()}catch{a.error({message:"Error fetching images!"})}finally{y(),r.target.reset()}});P.addEventListener("click",async()=>{n+=1,b(),p();try{const r=await d(i,n);g(r.hits),$();const e=Math.ceil(r.totalHits/L);n>=e?a.info({message:"We're sorry, but you've reached the end of search results."}):h()}catch{a.error({message:"Error loading more images!"})}finally{y()}});function $(){const r=document.querySelector(".gallery-item");if(r){const e=r.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
